spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graduateproject
    username: root
    password: root
  thymeleaf:
    cache: false
    cache-period: 0
  templates:
    cache: false
